# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
#
# NOTE: This workflow is overkill for most R packages and
# check-standard.yaml is likely a better choice.
# usethis::use_github_action("check-standard") will install it.
on:
  push:
    branches:
      - main
      - master
      - "r-*"
  pull_request:
    branches:
      - main
      - master
      - "r-*"
  schedule:
    - cron:  '10 0 * * *'

name: rcc

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) ${{ matrix.config.desc }}

    # Begin custom: services
    # End custom: services

    strategy:
      fail-fast: false
      # Ensure that the "cancel" workflow gets a chance to run quickly, even if we just pushed
      # Need to figure out how to smoke-test
      max-parallel: 5
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      # prevent rgl issues because no X11 display is available
      RGL_USE_NULL: true
      _R_CHECK_SYSTEM_CLOCK_: false
      _R_CHECK_FUTURE_FILE_TIMESTAMPS_: false
      # Begin custom: env vars
      # End custom: env vars

    steps:
      - name: Check rate limits
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash

      - uses: actions/checkout@v2

      # Begin custom: before install
      # End custom: before install

      - uses: r-lib/actions/setup-pandoc@v1

      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v1
        with:
          extra-packages: rcmdcheck

      - name: Add fake qpdf and checkbashisms
        if: runner.os == 'Linux'
        run: |
          sudo ln -s $(which true) /usr/local/bin/qpdf
          sudo ln -s $(which true) /usr/local/bin/checkbashisms

      - name: Session info
        run: |
          options(width = 100)
          if (!requireNamespace("sessioninfo", quietly = TRUE)) install.packages("sessioninfo")
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
        shell: Rscript {0}

      # Begin custom: after install
      # Must happen after installing system dependencies,
      # https://github.com/ankane/setup-mariadb/issues/2
      - uses: ankane/setup-postgres@v1
        with:
          postgres-version: 14

      - name: Create database
        if: runner.os != 'Windows'
        run: |
          createdb ${USER}

      - name: Create database
        if: runner.os == 'Windows'
        run: |
          createdb ${USERNAME}
        shell: bash
      # End custom: after install

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true

      - uses: r-lib/actions/check-r-package@v1

      - name: Show test output
        if: always()
        run: |
          find check -name '*.Rout*' -exec head -n 1000000 '{}' \; || true
        shell: bash

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check

      - name: Check rate limits
        if: always()
        run: |
          curl -s --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/rate_limit
        shell: bash
